### ISSUE TITLE
iPhone 6+ ScrollView blocking when we drag item a little

### ISSUE THREAD

**Issue by flypaper0** [thiagoperes/IDMPhotoBrowser#167]
iPhone 6+ ScrollView blocking when we drag item a little. After that scrolling is disabled. 

Screencast: https://drive.google.com/file/d/0BxAQ9t8IdD3SVS13dGFFWTA4cVk/view

**Comment by Shazib** [comment]
Maybe you could try the fix in this issue as that was a similar problem (for me)
https://github.com/ideaismobile/IDMPhotoBrowser/issues/132
