### ISSUE TITLE
change share button color. 

### ISSUE THREAD

**Issue by heisen273** [thiagoperes/IDMPhotoBrowser#238]
I am looking for any way to access and edit default IDMPhotoBrowser share button, but I cannot understand how to do that.
Is the only way to modify default share button state is creating my own? 

If anyone has knowledge, – please share it with me. 
Thanks

**Comment by rogomantik** [comment]
you can use
`browser.view.tintColor = UIColor.red`
seems to change only the share button tint

**Comment by heisen273** [comment]
thanks, @rogomantik , it actually did worked. 
one hint for other devs, on how you should actually use `browser.view.tintColor = UIColor.red`:
place it in `didShowPhotoAt` delegate, otherwise you might end up with doubling your image captions.
